/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ShootingStars {
    'height': string;
    'image': string;
    'space': number;
    'width': string;
  }
  interface ShootingStarsAttributes extends StencilHTMLAttributes {
    'height'?: string;
    'image'?: string;
    'space'?: number;
    'width'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ShootingStars': Components.ShootingStars;
  }

  interface StencilIntrinsicElements {
    'shooting-stars': Components.ShootingStarsAttributes;
  }


  interface HTMLShootingStarsElement extends Components.ShootingStars, HTMLStencilElement {}
  var HTMLShootingStarsElement: {
    prototype: HTMLShootingStarsElement;
    new (): HTMLShootingStarsElement;
  };

  interface HTMLElementTagNameMap {
    'shooting-stars': HTMLShootingStarsElement
  }

  interface ElementTagNameMap {
    'shooting-stars': HTMLShootingStarsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
